<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kf_categoryfilter"
 *
 * Auto generated by Extension Builder 2017-01-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'KF - Category Filter',
    'description' => 'Display sys_category in an other way.',
    'category' => 'plugin',
    'author' => 'Marc Finnern',
    'author_email' => 'typo3@klickfabrik.net',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.3',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.6.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
    'clearcacheonload' => true,
);